import { useState, useEffect } from 'react'

import './Options.css'

export const Options = () => {
  const link = 'https://github.com/guocaoyi/create-chrome-ext'
  return (
    <main>
      <h3>Options Page</h3>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Options
