import { useState, useEffect } from 'react'

import './SidePanel.css'

export const SidePanel = () => {
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  return (
    <main>
      <h3>SidePanel Page</h3>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default SidePanel
